AllCops:
  NewCops: enable

# Personal preferences
Layout/LineLength:
  Max: 120

Style/BlockDelimiters:
  EnforcedStyle: semantic

# DragonRuby basic

# Meaningless in mruby
Style/FrozenStringLiteralComment:
  Enabled: false

# Not implemented in mruby
Style/RandomWithOffset:
  Enabled: false

# Typical parameters/attributes for DragonRuby primitives
Naming/MethodParameterName:
  AllowedNames:
    - x
    - y
    - w
    - h
    - r
    - g
    - b

Style/GlobalVars:
  AllowedVariables:
    - $gtk
    - $game
    - $entity_store

Metrics/MethodLength:
  Exclude:
    - mygame/tests/**/*

Style/Documentation:
  Exclude:
    - mygame/tests/**/*
